import { Toaster } from "@/components/ui/sonner";
import "./globals.css";


export const metadata = {
  title: "Deal Drop",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={``}
      >
        {children}
        <Toaster richColors />
      </body>
    </html>
  );
}
